# Generated by Django 4.1.1 on 2022-09-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_daily_menu_votemenus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votemenus',
            options={'verbose_name': 'Vote Menu', 'verbose_name_plural': 'Menus for vote'},
        ),
        migrations.AlterField(
            model_name='votemenus',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
