# Generated by Django 4.1.1 on 2022-09-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_restaurant_id_alter_customuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
